import { Inter } from "next/font/google";
import "./globals.css";
import Script from "../node_modules/next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Script src="https://accounts.google.com/gsi/client" async defer />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
